### ISSUE TITLE
Not properly working with Redux React Typescript

### ISSUE THREAD

**Issue by iqasim-com** [joyceworks/flowchart-react#22]
Hi, it's an awesome package I love it but I am facing some issues when I used this with Redux.

## Version information
<img width="417" alt="image" src="https://user-images.githubusercontent.com/23281307/179145944-49bdefcb-15ad-43b6-8fde-23182e7fb875.png">

If I use the package without redux it's working fine. Only facing issue in Redux
## Redux implementation

Getting updated state from store successfully
<img width="838" alt="image" src="https://user-images.githubusercontent.com/23281307/179146697-141f34a1-d33c-46e2-8e69-fee791db9e8e.png">

Type is Also NodeData[]
<img width="413" alt="image" src="https://user-images.githubusercontent.com/23281307/179146769-e4b23f43-4d5b-473a-8ab6-491140a51cb1.png">

Store values: Getting array of objects
<img width="220" alt="image" src="https://user-images.githubusercontent.com/23281307/179146841-7752b1f0-e52e-404d-be41-324ea064cc2b.png">

After the above implementation I'm getting the following error:
<img width="559" alt="image" src="https://user-images.githubusercontent.com/23281307/179146957-14b6f0f8-1ba9-466f-828d-d5ce257ad37b.png">

**Comment by iamppz** [comment]
Hi, sorry that I'm not familiar with Redux, but I think there's a bug at [here](https://github.com/joyceworks/flowchart-react/blob/635cddbee9a2ccb351c98df20b134200e559d70e/src/index.tsx#L651):
```typescript
const nodeElements = useMemo(() => {
      return nodes?.map((node) => {
        node.width = node.width || defaultNodeSize.width;
        node.height = node.height || defaultNodeSize.height;
        return ...
      });
}, []);
```
I fixed it and pushed 3.6.3 to NPM, can you please upgrade the package and try it again?
